# Environment settings
name: DeepSea
depth: 5
deterministic_transition: false
penalty: 0.03
sto_trans_prob: 0.05
randomised_actions: true
randomised_action_seed: null

# Experiment settings
method: cdf
epsilon: 0.01
sigma: 10
num_episodes: 100
use_qmc: false
qmc_sobol_power: 15
output_obs: true